In [825]:
#pip install psycopg2-binary

In [826]:
#pip install ipython-sql sqlalchemy pandas

Importing sql extension

In [ ]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%load_ext sql
#%sql postgresql://postgres@localhost:5432/postgres

Creating a database connection

In [828]:
import pandas as pd
from sqlalchemy import create_engine
conn = create_engine('postgresql://postgres:Sefako61@localhost:5432/postgres')

Drops all the tables if i want to restart everything

In [ ]:
%%sql
DROP TABLE IF EXISTS sales_target, suppliers, orders, certification, harvest CASCADE;

Loading sales_target, orders and supplier data into the notebook

In [830]:
sale= pd.read_csv("/Users/tshmacm1175/Downloads/sales_targets.csv")
sale

   region_id         region  quarter  year  target_amount
0          1   Western Cape        4  2025          50000
1          2   Eastern Cape        4  2025          20000
2          3  Northern Cape        4  2025          30000

In [831]:
supply = pd.read_csv("/Users/tshmacm1175/Downloads/suppliers.csv")
supply

   supplier_id  region_id                farm_name
0            1          3        Karoo Lamb Estate
1            2          3     Desert Rose Orchards
2            3          2        Grootfontein Wool
3            4          1  Mountain View Vineyards
4            5          1        Valley Olive Farm
5            6          2        Blue Crane Citrus

In [832]:
data = pd.read_csv("/Users/tshmacm1175/Downloads/orders.csv")
data

    order_id  supplier_id  order_date  total_price
0          1            1  2025-10-05         5200
1          2            2  2025-10-12         8000
2          3            4  2025-10-15        12000
3          4            3  2025-10-20         3500
4          5            5  2025-11-02         9500
5          6            6  2025-11-10         7800
6          7            1  2025-11-15         4500
7          8            2  2025-11-20         9200
8          9            4  2025-12-01        15500
9         10            5  2025-12-10        11000
10        11            3  2025-12-15         4200

Creating tables for sales_target, orders and suppliers so that they can be loaded into the database

In [ ]:
%%sql create table sales_target (
region_id SERIAL PRIMARY KEY,
region VARCHAR(255),
quarter int,
year INT,
target_amount FLOAT
);

In [ ]:
%%sql Create table suppliers(
    supplier_id SERIAL PRIMARY KEY,
    region_id int,
    farm_name VARCHAR(255)
);

In [ ]:
%%sql Create table orders(
    order_id SERIAL PRIMARY KEY,
    supplier_id int,
    order_date DATE,
    total_price FLOAT
)

Added two columns into the supplier table

In [ ]:
%%sql
ALTER TABLE suppliers
add column phone_number VARCHAR(20), 
add column  email_address VARCHAR(50);

Automating supplier table and adding data into the last created columns

In [ ]:
sid = supply['supplier_id']
rid = supply['region_id']
fn = supply['farm_name']
pn= ['0211515121','0211011481','0212198774','0211116110','0211819249','0218461011']
ed = ['karoo@gmail.com','desert@gmail.com','wool@gmail.com','view@gmail.com','farm@gmail.com','blue@gmail.com']



for sid, rid, fn, pn, ed in zip(sid, rid, fn, pn, ed):
    %sql insert into suppliers (supplier_id, region_id, farm_name, phone_number, email_address) values (:sid, :rid, :fn, :pn, :ed) on conflict do nothing;

In [838]:
%sql select * from suppliers

 * postgresql://postgres@localhost:5432/postgres
6 rows affected.

[(1, 3, 'Karoo Lamb Estate', '0211515121', 'karoo@gmail.com'),
 (2, 3, 'Desert Rose Orchards', '0211011481', 'desert@gmail.com'),
 (3, 2, 'Grootfontein Wool', '0212198774', 'wool@gmail.com'),
 (4, 1, 'Mountain View Vineyards', '0211116110', 'view@gmail.com'),
 (5, 1, 'Valley Olive Farm', '0211819249', 'farm@gmail.com'),
 (6, 2, 'Blue Crane Citrus', '0218461011', 'blue@gmail.com')]

Automating sales_target and orders table

In [ ]:
rid = sale.region_id
r = sale.region
q = sale.quarter
y = sale.year
ta = sale.target_amount

for rid, r, q, y, ta in zip(rid, r, q, y, ta):
    %sql insert into sales_target (region_id, region, quarter, year, target_amount) values (:rid, :r, :q, :y, :ta) on conflict do nothing;

In [840]:
%sql select * from sales_target;

 * postgresql://postgres@localhost:5432/postgres
3 rows affected.

[(1, 'Western Cape', 4, 2025, 50000.0),
 (2, 'Eastern Cape', 4, 2025, 20000.0),
 (3, 'Northern Cape', 4, 2025, 30000.0)]

In [ ]:
oid = data.order_id
sid = data.supplier_id
od = data.order_date
tp = data.total_price

for oid, sid, od, tp in zip(oid, sid, od, tp):
    %sql insert into orders (order_id, supplier_id, order_date, total_price) values (:oid, :sid, :od, :tp);

In [842]:
%sql select * from orders;

 * postgresql://postgres@localhost:5432/postgres
11 rows affected.

[(1, 1, datetime.date(2025, 10, 5), 5200.0),
 (2, 2, datetime.date(2025, 10, 12), 8000.0),
 (3, 4, datetime.date(2025, 10, 15), 12000.0),
 (4, 3, datetime.date(2025, 10, 20), 3500.0),
 (5, 5, datetime.date(2025, 11, 2), 9500.0),
 (6, 6, datetime.date(2025, 11, 10), 7800.0),
 (7, 1, datetime.date(2025, 11, 15), 4500.0),
 (8, 2, datetime.date(2025, 11, 20), 9200.0),
 (9, 4, datetime.date(2025, 12, 1), 15500.0),
 (10, 5, datetime.date(2025, 12, 10), 11000.0),
 (11, 3, datetime.date(2025, 12, 15), 4200.0)]

Creating and automating tables for certification and harvest table

In [ ]:
%%sql create table certification (
    cert_id SERIAL PRIMARY KEY,
    supplier_id int ,
    cert_name VARCHAR(50),
    expiry_date DATE
);

In [ ]:
sid =[4,4,1,5,2,1]
cn = ['Fair trade','Good harvest', 'Fair trade', 'Organic', 'Fair trade', 'Organic']
ed = ['2026-12-30','2026-12-30','2026-06-11','2026-08-30','2026-05-30','2026-04-30']

for sid,cn,ed in zip(sid,cn,ed):
    %sql insert into certification (supplier_id, cert_name, expiry_date) values (:sid, :cn, :ed);

In [845]:
%sql select * from certification;

 * postgresql://postgres@localhost:5432/postgres
6 rows affected.

[(1, 4, 'Fair trade', datetime.date(2026, 12, 30)),
 (2, 4, 'Good harvest', datetime.date(2026, 12, 30)),
 (3, 1, 'Fair trade', datetime.date(2026, 6, 11)),
 (4, 5, 'Organic', datetime.date(2026, 8, 30)),
 (5, 2, 'Fair trade', datetime.date(2026, 5, 30)),
 (6, 1, 'Organic', datetime.date(2026, 4, 30))]

In [ ]:
%%sql create table harvest(
    harvest_id  SERIAL PRIMARY KEY,
    supplier_id int,
    crop_name VARCHAR(50),
    harvest_date DATE,
    yield_kg float

)

In [ ]:


sid = [4,5,4,1,5,2,4,6,5]
cn = ['Wheat', 'Beetroot', 'Cherries', 'Wheat', 'Oats', 'Beetroot', 'Potatoes', 'Oats', 'Berries']
hd = ['2025-09-30','2025-10-11', '2025-09-30', '2025-09-11', '2025-10-15', '2025-09-20', '2025-09-21', '2025-10-11', '2025-10-02']
yk = [1000, 500, 2000, 1500, 800, 1200, 3000, 900, 400]

for si, c, h, y in zip(sid, cn, hd, yk):
    %sql INSERT INTO harvest (supplier_id, crop_name, harvest_date, yield_kg) VALUES (:si, :c, :h, :y) ;

In [848]:
%sql select * from harvest

 * postgresql://postgres@localhost:5432/postgres
9 rows affected.

[(1, 4, 'Wheat', datetime.date(2025, 9, 30), 1000.0),
 (2, 5, 'Beetroot', datetime.date(2025, 10, 11), 500.0),
 (3, 4, 'Cherries', datetime.date(2025, 9, 30), 2000.0),
 (4, 1, 'Wheat', datetime.date(2025, 9, 11), 1500.0),
 (5, 5, 'Oats', datetime.date(2025, 10, 15), 800.0),
 (6, 2, 'Beetroot', datetime.date(2025, 9, 20), 1200.0),
 (7, 4, 'Potatoes', datetime.date(2025, 9, 21), 3000.0),
 (8, 6, 'Oats', datetime.date(2025, 10, 11), 900.0),
 (9, 5, 'Berries', datetime.date(2025, 10, 2), 400.0)]

Analytical queries for region, actual revenue, target amount, % of target using case and group by

In [849]:
%%sql select sum(total_price)  as actual_revenue, target_amount, region,


case
    when target_amount > 0 
    then round(((sum(total_price) / target_amount) * 100) ::numeric, 2)
    else 0
end as target_sales_percentage


from suppliers right join orders on orders.supplier_id = suppliers.supplier_id
            left join sales_target on sales_target.region_id = suppliers.region_id
            group by target_amount , region

 * postgresql://postgres@localhost:5432/postgres
3 rows affected.

[(48000.0, 50000.0, 'Western Cape', Decimal('96.00')),
 (26900.0, 30000.0, 'Northern Cape', Decimal('89.67')),
 (15500.0, 20000.0, 'Eastern Cape', Decimal('77.50'))]

Analytical queries for ranking top 3 suppliers per region by revenue using rank and partition by

In [850]:
%%sql 
with ranked_revenue as (   

select sum(total_price) as total_revenue , farm_name, region,


rank() over(partition by region
order by sum(total_price)  desc
) as revenue_rank 

from suppliers right join orders on orders.supplier_id = suppliers.supplier_id
            left join sales_target on sales_target.region_id = suppliers.region_id
            group by target_amount , region, farm_name  
)
select * 
from ranked_revenue
where revenue_rank = 1

 * postgresql://postgres@localhost:5432/postgres
3 rows affected.

[(7800.0, 'Blue Crane Citrus', 'Eastern Cape', 1),
 (17200.0, 'Desert Rose Orchards', 'Northern Cape', 1),
 (27500.0, 'Mountain View Vineyards', 'Western Cape', 1)]