In [ ]:
pip install psycopg2-binary

In [ ]:
pip install ipython-sql sqlalchemy pandas

In [45]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%load_ext sql
%sql postgresql://postgres:Sefako61@localhost:5432/postgres

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [46]:
import pandas as pd
from sqlalchemy import create_engine
conn = create_engine('postgresql://postgres:Sefako61@localhost:5432/postgres')

In [47]:
sale= pd.read_csv("C:\\Users\\kamok\\Downloads\\Sales_Target.csv")
sale

   region_id         region  quarter  target_amount
0          1   Western Cape  2025-Q4          50000
1          2   Eastern Cape  2025-Q4          20000
2          3  Northern Cape  2025-Q4          30000

In [48]:
sale.to_sql('sales_target', conn, if_exists = 'replace', index = False);

In [49]:
%sql SELECT * FROM sales_target;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.

[(1, 'Western Cape', '2025-Q4', 50000),
 (2, 'Eastern Cape', '2025-Q4', 20000),
 (3, 'Northern Cape', '2025-Q4', 30000)]

In [50]:
supply = pd.read_csv("C:\\Users\\kamok\\Downloads\\Suppliers.csv")
supply

   supplier_id  region_id                farm_name
0            1          3        Karoo Lamb Estate
1            2          3     Desert Rose Orchards
2            3          2        Grootfontein Wool
3            4          1  Mountain View Vineyards
4            5          1        Valley Olive Farm
5            6          2        Blue Crane Citrus

In [51]:
supply.to_sql('suppliers', conn, if_exists='replace', index=False)

6

In [52]:
%sql select * from suppliers;

 * postgresql://postgres:***@localhost:5432/postgres
6 rows affected.

[(1, 3, 'Karoo Lamb Estate'),
 (2, 3, 'Desert Rose Orchards'),
 (3, 2, 'Grootfontein Wool'),
 (4, 1, 'Mountain View Vineyards'),
 (5, 1, 'Valley Olive Farm'),
 (6, 2, 'Blue Crane Citrus')]

In [53]:
data = pd.read_csv("C:\\Users\\kamok\\Downloads\\Orders.csv")
data

    order_id  supplier_id  order_date  total_price
0          1            1  2025-10-05         5200
1          2            2  2025-10-12         8000
2          3            4  2025-10-15        12000
3          4            3  2025-10-20         3500
4          5            5  2025-11-02         9500
5          6            6  2025-11-10         7800
6          7            1  2025-11-15         4500
7          8            2  2025-11-20         9200
8          9            4  2025-12-01        15500
9         10            5  2025-12-10        11000
10        11            3  2025-12-15         4200

In [54]:
data.to_sql('orders', conn, if_exists='replace', index=False)

11

In [ ]:
%%sql 
SELECT supplier_id, COUNT(*)
FROM suppliers
GROUP BY supplier_id
HAVING COUNT(*) > 1;

In [ ]:
%%sql
SELECT supplier_id, COUNT(*) AS count
FROM orders
GROUP BY supplier_id
HAVING COUNT(*) > 1
ORDER BY count DESC;

In [ ]:
%%sql
DELETE FROM suppliers a
USING suppliers b
WHERE a.ctid < b.ctid
AND a.supplier_id = b.supplier_id;

In [ ]:
%%sql
ALTER TABLE suppliers
add column phone_number VARCHAR(20), 
add column  email_address VARCHAR(50);

In [ ]:
sid = supply['supplier_id']
rid = supply['region_id']
fn = supply['farm_name']


for sid, rid, fn in zip(sid, rid, fn):
    %sql insert into suppliers (supplier_id, region_id, farm_name) values (:sid, :rid, :fn)

In [ ]:
pn= ['0211515121','0211011481','0212198774','0211116110','0211819249','0218461011']
ed = ['karoo@gmail.com','desert@gmail.com','wool@gmail.com','view@gmail.com','farm@gmail.com','blue@gmail.com']
sid = [1,2,3,4,5,6]
for pn, ed, sid in zip(pn, ed, sid):
    %sql update suppliers set phone_number = :pn, email_address = :ed where supplier_id = :sid;

In [ ]:
rid = sale.region_id
r = sale.region
q = sale.quarter
ta = sale.target_amount

for rid, r, q, ta in zip(rid, r, q, ta):
    %sql insert into sales_target (region_id, region, quantity, target_amount) values (:rid, :r, :q, :ta);

In [ ]:
oid = data.order_id
sid = data.supplier_id
od = data.order_date
tp = data.total_price

for oid, sid, od, tp in zip(oid, sid, od, tp):
    %sql insert into orders (order_id, supplier_id, order_date, total_price) values (:oid, :sid, );

In [ ]:
%%sql create table certification (
    cert_id SERIAL PRIMARY KEY,
    supplier_id int,
    cert_name VARCHAR(50),
    expiry_date DATE
);

In [ ]:
sid =[4,4,1,5,2,1]
cn = ['Fair trade','Good harvest', 'Fair trade', 'Organic', 'Fair trade', 'Organic']
ed = ['2026-12-30','2026-12-30','2026-06-11','2026-08-30','2026-05-30','2026-04-30']

for sid,cn,ed in zip(sid,cn,ed):
    %sql insert into certification (supplier_id, cert_name, expiry_date) values (:sid, :cn, :ed);

In [ ]:
%%sql create table harvest(
    harvest_id SERIAL PRIMARY KEY,
    supplier_id int,
    crop_name VARCHAR(50),
    harvest_date DATE,
    yield_kg int

)

In [ ]:
sid = [4,5,4,1,5,2,4,6,5]
cn = ['Wheat', 'Beetroot', 'Cherries', 'Wheat', 'Oats', 'Beetroot', 'Potatoes', 'Oats', 'Berries']
hd = ['2025-09-30','2025-10-11', '2025-09-30', '2025-09-11', '2025-10=15', '2025-09-20', '2025-09-21', '2025-10-11', '2025-10-02']
yk = [1000, 500, 2000, 1500, 800, 1200, 3000, 900, 400]

for sid, cn, hd, yk in zip( sid, cn, hd, yk):
    %sql insert  into harvest ( supplier_id, crop_name, harvest_date, yield_kg) values (:sid, :cn, :hd, :yk);

In [ ]:
%sql select * from suppliers;

In [ ]:
%sql select * from sales_target;

In [ ]:
%sql select * from orders;