In [350]:
#pip install psycopg2-binary

In [351]:
#pip install ipython-sql sqlalchemy pandas

Importing sql

In [352]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%load_ext sql
%sql postgresql://postgres@localhost:5432/postgres

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Creating a database connection

In [353]:
import pandas as pd
from sqlalchemy import create_engine
conn = create_engine('postgresql://postgres:Sefako61@localhost:5432/postgres')

Loading data into the notebook

In [354]:
sale= pd.read_csv("/Users/tshmacm1175/Downloads/sales_targets.csv")
sale

   region_id         region  quarter  year  target_amount
0          1   Western Cape        4  2025          50000
1          2   Eastern Cape        4  2025          20000
2          3  Northern Cape        4  2025          30000

In [355]:
supply = pd.read_csv("/Users/tshmacm1175/Downloads/suppliers.csv")
supply

   supplier_id  region_id                farm_name
0            1          3        Karoo Lamb Estate
1            2          3     Desert Rose Orchards
2            3          2        Grootfontein Wool
3            4          1  Mountain View Vineyards
4            5          1        Valley Olive Farm
5            6          2        Blue Crane Citrus

In [356]:
data = pd.read_csv("/Users/tshmacm1175/Downloads/orders.csv")
data

    order_id  supplier_id  order_date  total_price
0          1            1  2025-10-05         5200
1          2            2  2025-10-12         8000
2          3            4  2025-10-15        12000
3          4            3  2025-10-20         3500
4          5            5  2025-11-02         9500
5          6            6  2025-11-10         7800
6          7            1  2025-11-15         4500
7          8            2  2025-11-20         9200
8          9            4  2025-12-01        15500
9         10            5  2025-12-10        11000
10        11            3  2025-12-15         4200

creating tables for the imported so that they can be loaded into the database

In [ ]:
%%sql create table sales_target (
region_id SERIAL PRIMARY KEY,
region VARCHAR(255),
quarter int,
year INT,
target_amount FLOAT
);

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateTable) relation "sales_target" already exists

[SQL: create table sales_target (
region_id SERIAL PRIMARY KEY,
region VARCHAR(255),
quarter int,
year INT,
target_amount FLOAT
);]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql Create table suppliers(
    supplier_id SERIAL PRIMARY KEY,
    region_id INT,
    farm_name VARCHAR(255)
);

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateTable) relation "suppliers" already exists

[SQL: Create table suppliers(
    supplier_id SERIAL PRIMARY KEY,
    region_id INT,
    farm_name VARCHAR(255)
);]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql Create table orders(
    order_id SERIAL PRIMARY KEY,
    supplier_id INT,
    order_date DATE,
    total_price FLOAT
)

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateTable) relation "orders" already exists

[SQL: Create table orders(
    order_id SERIAL PRIMARY KEY,
    supplier_id INT,
    order_date DATE,
    total_price FLOAT
)]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql
ALTER TABLE suppliers
add column phone_number VARCHAR(20), 
add column  email_address VARCHAR(50);

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateColumn) column "phone_number" of relation "suppliers" already exists

[SQL: ALTER TABLE suppliers
add column phone_number VARCHAR(20),
add column  email_address VARCHAR(50);]
(Background on this error at: https://sqlalche.me/e/20/f405)

Automating supplier table

In [ ]:
sid = supply['supplier_id']
rid = supply['region_id']
fn = supply['farm_name']
pn= ['0211515121','0211011481','0212198774','0211116110','0211819249','0218461011']
ed = ['karoo@gmail.com','desert@gmail.com','wool@gmail.com','view@gmail.com','farm@gmail.com','blue@gmail.com']



for sid, rid, fn, pn, ed in zip(sid, rid, fn, pn, ed):
    %sql insert into suppliers (supplier_id, region_id, farm_name, phone_number, email_address) values (:sid, :rid, :fn, :pn, :ed)

 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.

In [ ]:
rid = sale.region_id
r = sale.region
q = sale.quarter
y = sale.year
ta = sale.target_amount

for rid, r, q, y, ta in zip(rid, r, q, y, ta):
    %sql insert into sales_target (region_id, region, quarter, year, target_amount) values (:rid, :r, :q, :y, :ta);

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.UndefinedColumn) column "year" of relation "sales_target" does not exist
LINE 1: ...rt into sales_target (region_id, region, quarter, year, targ...
                                                             ^

[SQL: insert into sales_target (region_id, region, quarter, year, target_amount) values (%(rid)s, %(r)s, %(q)s, %(y)s, %(ta)s);]
[parameters: {'rid': 1, 'r': 'Western Cape', 'q': 4, 'y': 2025, 'ta': 50000}]
(Background on this error at: https://sqlalche.me/e/20/f405)
 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.UndefinedColumn) column "year" of relation "sales_target" does not exist
LINE 1: ...rt into sales_target (region_id, region, quarter, year, targ...
                                                             ^

[SQL: insert into sales_target (region_id, region, quarter, year, target_amount) values (%(rid)s, %(r)s, %(q)s, %(y)s, %(ta)s);]
[parameters: {'rid': 2, 'r': 'Eastern Cape', 'q': 4, 'y': 2025, 'ta': 20000}]
(Background on this error at: https://sqlalche.me/e/20/f405)
 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.UndefinedColumn) column "year" of relation "sales_target" does not exist
LINE 1: ...rt into sales_target (region_id, region, quarter, year, targ...
                                                             ^

[SQL: insert into sales_target (region_id, region, quarter, year, target_amount) values (%(rid)s, %(r)s, %(q)s, %(y)s, %(ta)s);]
[parameters: {'rid': 3, 'r': 'Northern Cape', 'q': 4, 'y': 2025, 'ta': 30000}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
oid = data.order_id
sid = data.supplier_id
od = data.order_date
tp = data.total_price

for oid, sid, od, tp in zip(oid, sid, od, tp):
    %sql insert into orders (order_id, supplier_id, order_date, total_price) values (:oid, :sid, :od, :tp);

 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.

Creating certification table and harvest table

In [ ]:
%%sql create table certification (
    cert_id SERIAL PRIMARY KEY,
    supplier_id int,
    cert_name VARCHAR(50),
    expiry_date DATE
);

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateTable) relation "certification" already exists

[SQL: create table certification (
    cert_id SERIAL PRIMARY KEY,
    supplier_id int,
    cert_name VARCHAR(50),
    expiry_date DATE
);]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
sid =[4,4,1,5,2,1]
cn = ['Fair trade','Good harvest', 'Fair trade', 'Organic', 'Fair trade', 'Organic']
ed = ['2026-12-30','2026-12-30','2026-06-11','2026-08-30','2026-05-30','2026-04-30']

for sid,cn,ed in zip(sid,cn,ed):
    %sql insert into certification (supplier_id, cert_name, expiry_date) values (:sid, :cn, :ed);

 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.

In [ ]:
%%sql create table harvest(
    harvest_id SERIAL PRIMARY KEY,
    supplier_id int,
    crop_name VARCHAR(50),
    harvest_date DATE,
    yield_kg int

)

 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.DuplicateTable) relation "harvest" already exists

[SQL: create table harvest(
    harvest_id SERIAL PRIMARY KEY,
    supplier_id int,
    crop_name VARCHAR(50),
    harvest_date DATE,
    yield_kg int

)]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
sid = [4,5,4,1,5,2,4,6,5]
cn = ['Wheat', 'Beetroot', 'Cherries', 'Wheat', 'Oats', 'Beetroot', 'Potatoes', 'Oats', 'Berries']
hd = ['2025-09-30','2025-10-11', '2025-09-30', '2025-09-11', '2025-10=15', '2025-09-20', '2025-09-21', '2025-10-11', '2025-10-02']
yk = [1000, 500, 2000, 1500, 800, 1200, 3000, 900, 400]

for sid, cn, hd, yk in zip( sid, cn, hd, yk):
    %sql insert  into harvest ( supplier_id, crop_name, harvest_date, yield_kg) values (:sid, :cn, :hd, :yk);

 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
(psycopg2.errors.InvalidDatetimeFormat) invalid input syntax for type date: "2025-10=15"
LINE 1: ..._name, harvest_date, yield_kg) values (5, 'Oats', '2025-10=1...
                                                             ^

[SQL: insert into harvest ( supplier_id, crop_name, harvest_date, yield_kg) values (%(sid)s, %(cn)s, %(hd)s, %(yk)s);]
[parameters: {'sid': 5, 'cn': 'Oats', 'hd': '2025-10=15', 'yk': 800}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.
 * postgresql://postgres@localhost:5432/postgres
1 rows affected.

Analytical queries for region, actual revenue, target amount, % of target using case and group by

In [ ]:
%%sql select sum(total_price)  as actual_revenue, target_amount, region,


case
    when target_amount > 0 
    then round(((sum(total_price) / target_amount) * 100) ::numeric, 2)
    else 0
end as target_sales_percentage


from suppliers right join orders on orders.supplier_id = suppliers.supplier_id
            left join sales_target on sales_target.region_id = suppliers.region_id
            group by target_amount , region

 * postgresql://postgres@localhost:5432/postgres
3 rows affected.

[(Decimal('564900'), 30000, 'Northern Cape', Decimal('1883.00')),
 (Decimal('1008000'), 50000, 'Western Cape', Decimal('2016.00')),
 (Decimal('325500'), 20000, 'Eastern Cape', Decimal('1627.50'))]

Analytical queries for ranking top 3 suppliers per region by revenue using rank and partition by

In [ ]:
%%sql 
with ranked_revenue as (   

select sum(total_price) as total_revenue , farm_name, region,


rank() over(partition by region
order by sum(total_price)  desc
) as revenue_rank 

from suppliers right join orders on orders.supplier_id = suppliers.supplier_id
            left join sales_target on sales_target.region_id = suppliers.region_id
            group by target_amount , region, farm_name  
)
select * 
from ranked_revenue
where revenue_rank = 1

 * postgresql://postgres@localhost:5432/postgres
3 rows affected.

[(Decimal('163800'), 'Blue Crane Citrus', 'Eastern Cape', 1),
 (Decimal('361200'), 'Desert Rose Orchards', 'Northern Cape', 1),
 (Decimal('577500'), 'Mountain View Vineyards', 'Western Cape', 1)]